### ISSUE TITLE
Non-uniform encoding

### ISSUE THREAD

**Issue by yigitsever** [Xangis/extra-stopwords#3]
While most of the stopwords are utf-8, iso-8859-1 encoded ones trip nltk because it expects utf-8 encoded stopword files.

- belarusian
- estonian
- hebrew
- slovenian

Ran into the issue while working with slovenian, did not test for other languages.

Fix should be an easy `iconv -f ISO-8859-1 -t UTF-8`, which solved the problem for my case.

**Comment by Xangis** [comment]
Thank you, I've updated the repository with the fixes from your suggestion.
