### ISSUE TITLE
Empty files after conversion to UTF-8

### ISSUE THREAD

**Issue by BLKSerene** [Xangis/extra-stopwords#5]
Hi, the files for [belarusian](https://github.com/Xangis/extra-stopwords/blob/master/belarusian), [estonian](https://github.com/Xangis/extra-stopwords/blob/master/estonian), [hebrew](https://github.com/Xangis/extra-stopwords/blob/master/hebrew), [slovenian ](https://github.com/Xangis/extra-stopwords/blob/master/slovenian)are all empty after being converted to UTF-8 (#3).

**Comment by Xangis** [comment]
There do seem to be some encoding issues. I'm not sure what the best way to fix that is, but if you have a fix I'd be happy to merge a pull request.

**Comment by BLKSerene** [comment]
Okay, #7 will fix this.
