### ISSUE TITLE
Difference between file farsi and file persian?

### ISSUE THREAD

**Issue by BLKSerene** [Xangis/extra-stopwords#6]
Hi, AFAIK Farsi and Persian refer to the same language, so what's the difference between file `farsi` and file `persian`, or should the two files be merged?

**Comment by Xangis** [comment]
I'm not certain the what difference is. I know there are two variants of farsi/persian (Afghanistan and Iran variants), but I don't know enough about the languages to merge them intelligently. I'd be happy to accept a pull request if you'd like to contribute improvements.

**Comment by kotasudeepthi** [comment]
how to include many languages in stopwords keyword..please reply I am doing a project I need to submit it soon
